site_name: The Ontology for Modeling and Representation of Social Entities
theme: readthedocs
nav:
  - Basics:
      - Overview: index.md
      - Cite: cite.md
      - History: history.md
  - Modeling:
      - Modeling home: modeling/Home.md
  - Editors Guide:
      - Standard ODK workflows:
          - Overview: odk-workflows/index.md
          - Editors Workflow: odk-workflows/EditorsWorkflow.md
          - Release Workflow: odk-workflows/ReleaseWorkflow.md
          - Manage your ODK Repository: odk-workflows/RepoManagement.md
          - Setting up Docker for ODK: odk-workflows/SettingUpDockerForODK.md
          - Imports management: odk-workflows/UpdateImports.md
          - Continuous Integration: odk-workflows/ContinuousIntegration.md
          - Your ODK Repository Overview: odk-workflows/RepositoryFileStructure.md 
      - OMRSE specific workflows:
          - Managing the documentation: omrse-doc-process/EditingOMRSEDocumentation.md
      - Contributing: contributing.md

