PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?iri ?label ?iso6391 ?iso6392b ?iso6392t ?iso6393
where {
	?iri rdf:type <http://purl.obolibrary.org/obo/OMRSE_00002069> .
	?iri rdfs:label ?label .
	?iri <http://purl.obolibrary.org/obo/OMRSE_00002025> ?iso6391 .
	OPTIONAL { ?iri <http://purl.obolibrary.org/obo/OMRSE_00002026> ?iso6392b } .
	OPTIONAL { ?iri <http://purl.obolibrary.org/obo/OMRSE_00002027> ?iso6392t } .
	OPTIONAL { ?iri <http://purl.obolibrary.org/obo/OMRSE_00002028> ?iso6393 }
}